#Sustitucion de Caracteres
	#Funcion que utilizaremos para realizar un replace de los caracteres no admitidos.
def sustitucionCaracter(cadena):
	cadena=cadena.replace('\xC0','A')
	cadena=cadena.replace('\xC1','A')
	cadena=cadena.replace('\xC2','A')
	cadena=cadena.replace('\xC3','A')
	cadena=cadena.replace('\xC4','A')
	cadena=cadena.replace('\xC5','A')
	cadena=cadena.replace('\xC6','A')
	cadena=cadena.replace('\xC7','C')
	cadena=cadena.replace('\xC8','E')
	cadena=cadena.replace('\xC9','E')
	cadena=cadena.replace('\xCA','E')
	cadena=cadena.replace('\xCB','E')
	cadena=cadena.replace('\xCC','I')
	cadena=cadena.replace('\xCD','I')
	cadena=cadena.replace('\xCE','I')
	cadena=cadena.replace('\xCF','I')
	cadena=cadena.replace('\xD0','D')
	cadena=cadena.replace('\xD1','N')
	cadena=cadena.replace('\xD2','O')
	cadena=cadena.replace('\xD3','O')
	cadena=cadena.replace('\xD4','O')
	cadena=cadena.replace('\xD5','O')
	cadena=cadena.replace('\xD6','O')
	cadena=cadena.replace('\xD8','O')
	cadena=cadena.replace('\xD9','U')
	cadena=cadena.replace('\xDA','U')
	cadena=cadena.replace('\xDB','U')
	cadena=cadena.replace('\xDC','U')
	cadena=cadena.replace('\xDD','Y')
	cadena=cadena.replace('\xDE','p')
	cadena=cadena.replace('\xDF','b')
	cadena=cadena.replace('\xE0','a')
	cadena=cadena.replace('\xE1','a')
	cadena=cadena.replace('\xE2','a')
	cadena=cadena.replace('\xE3','a')
	cadena=cadena.replace('\xE4','a')
	cadena=cadena.replace('\xE5','a')
	cadena=cadena.replace('\xE6','a')
	cadena=cadena.replace('\xE7','c')
	cadena=cadena.replace('\xE8','e')
	cadena=cadena.replace('\xE9','e')
	cadena=cadena.replace('\xEA','e')
	cadena=cadena.replace('\xEB','e')
	cadena=cadena.replace('\xEC','i')
	cadena=cadena.replace('\xED','i')
	cadena=cadena.replace('\xEE','i')
	cadena=cadena.replace('\xEF','i')
	cadena=cadena.replace('\xF0','o')
	cadena=cadena.replace('\xF1','n')
	cadena=cadena.replace('\xF2','o')
	cadena=cadena.replace('\xF3','o')
	cadena=cadena.replace('\xF4','o')
	cadena=cadena.replace('\xF5','o')
	cadena=cadena.replace('\xF6','o')
	cadena=cadena.replace('\xF8','o')
	cadena=cadena.replace('\xF9','u')
	cadena=cadena.replace('\xFA','u')
	cadena=cadena.replace('\xFB','u')
	cadena=cadena.replace('\xFC','u')
	cadena=cadena.replace('\xFD','y')
	cadena=cadena.replace('\xFE','p')
	cadena=cadena.replace('\xFF','y')
	cadena=cadena.replace('\u0152','ce')
	cadena=cadena.replace('\u0153','oe')
	cadena=cadena.replace('\u0160','s')
	cadena=cadena.replace('\u0161','s')
	cadena=cadena.replace('\u0178','y')
	cadena=cadena.replace('\u0192','f')
	cadena=cadena.replace('\xaa','a')
	cadena=cadena.replace('\x80','eu')
        cadena=cadena.replace('\x7B','C')
        cadena=cadena.replace('\x7C','I')
        cadena=cadena.replace('\x7D','C')
        cadena=cadena.replace('\x7E','s')
        cadena=cadena.replace('\x5B','C')
        cadena=cadena.replace('\x5C','I')
        cadena=cadena.replace('\x5D','C')
        cadena=cadena.replace('\x5E','a')
        cadena=cadena.replace('\x5F','l')
        cadena=cadena.replace('\x23',' ')
        cadena=cadena.replace('\x24','eu')
        cadena=cadena.replace('\x25','100')
        cadena=cadena.replace('\x26','Y')
        cadena=cadena.replace('\x27',' ')
        cadena=cadena.replace('\x28',' ')
        cadena=cadena.replace('\x29',' ')
        cadena=cadena.replace('\x2A',' ')
        cadena=cadena.replace('\x2B',' ')
        cadena=cadena.replace('\x2C',' ')
        cadena=cadena.replace('\x2E',' ')
        cadena=cadena.replace('\x2F',' ')
        cadena=cadena.replace('\x60',' ')
        cadena=cadena.replace('\x3C','menor')
        cadena=cadena.replace('\x3D','igual')
        cadena=cadena.replace('\x3E','mayor')
        cadena=cadena.replace('\x3F',' ')
        cadena=cadena.replace('\x20',' ')
        cadena=cadena.replace('\x40','a')
        cadena=cadena.replace('\x21',' ')
        cadena=cadena.replace('\x22',' ')
	cadena=cadena.replace('\xae',' ')
	cadena=cadena.replace('\xaf',' ')
        cadena=cadena.replace('\x07','G')
        cadena=cadena.replace('\xab',' ')
        cadena=cadena.replace('\x0b','K')
	cadena=cadena.replace('\xb0',' ')	
	cadena=cadena.replace('\xba',' ')
	cadena=cadena.replace('\xa0',' ')
	cadena=cadena.replace('\x96',' ')
	cadena=cadena.replace('\0',' ')
	cadena=cadena.replace('\xb1','n')
        cadena=cadena.replace('\xa9','C')
 	cadena=cadena.replace('\xad','i')
 	cadena=cadena.replace('\xa1','n')
 	cadena=cadena.replace('\xb3','o')
        cadena=cadena.replace('\x81','')
        cadena=cadena.replace('\xbc','u')
        cadena=cadena.replace('\xb4','')

	cadena=cadena.replace('\x89','e')
        cadena=cadena.replace('\xac','')
        cadena=cadena.replace('\x9a','u')
        cadena=cadena.replace('\xa6','')
        cadena=cadena.replace('\x9c','')
        cadena=cadena.replace('\x9d','')
        cadena=cadena.replace('\xbd','')
        cadena=cadena.replace('\x93','o')
        cadena=cadena.replace('\xa8','')
        #cadena=cadena.replace('\x','')








        return cadena
#Sustitucion de Caracteres





